config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes
  get 'welcome/index'

  root 'recipes#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.try(:admin?)
      can :manage, :all
    else
      can :update, Recipe do |recipe|
          recipe.user == user
      end

      can :destroy, Recipe do |recipe|
          recipe.user == user
      end
      can :create, Recipe
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end

  has_attached_file :image, styles: { medium: "300x300#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :user

  has_many :ingredients, dependent: :destroy
  has_many :directions, dependent: :destroy

  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

  validates :title, :description, :image, :ingredients, :directions, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #check_authorization :unless => :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end

        rescue_from CanCan::AccessDenied do |exception|
          redirect_to recipes_url, :alert => exception.message
        end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  #skip_authorization_check :except => [:new, :edit, :update, :destroy]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.order("created_at DESC")
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit
    authorize! :update, @recipe
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :slug, :image, :user_id, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
    end

    def find_recipe
      @recipe = Recipe.friendly.find(params[:id])
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #skip_authorization_check
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:viewport => "width=device-width, initial scale=1"}/
    %title Nicolesrecipes | Your source for the best recipes around
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-brand= link_to "Nicole's Recipes", root_path

        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "New Recipe", new_recipe_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Home", root_path
            %li= link_to "Blog", "#"



    .container
      - flash.each do |name, msg|
        = content_tag :div, msg, class: "alert"

    = yield
<br/>
<br/>

app/views/recipes/_direction_fields.html.haml
.form-new-recipe
  .form-inline.clearfix
    .nested-fields
      = f.input :step, input_html: { class: 'form-input form-control' }
      = link_to_remove_association "Remove Step", f, class: "btn btn-default form-button"

app/views/recipes/_form.html.haml
.form-new-recipe
	= simple_form_for(@recipe, html: { multipart: true, class: 'form-horizontal' }) do |f|
		- if @recipe.errors.any?
			#errors
				%p
					= @recipe.errors.count
					Errors prevented this recipe from saving. Please correct the errors listed below.
				%ul
					- @recipe.errors.full_messages.each do |msg|
						%li= msg
		.panel-body
			= f.input :title, input_html: { class: 'form-control' }
			= f.input :description, input_html: { class: 'form-control' }
			= f.input :image, input_html: { class: 'form-control' }

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button"

			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"

		= f.button :submit, class: "btn btn-success"
		= link_to 'Cancel', recipes_path, class: "btn btn-danger"

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
  .nested-fields
    = f.input :name, input_html: { class: 'form-input form-control' }
    = link_to_remove_association "Remove", f, class: "form-button btn btn-default"

app/views/recipes/edit.html.haml
.container
  %h1 Edit Recipe

  = render 'form'

  %br/

  = link_to 'All Recipes', recipes_path, class: "btn btn-primary"
  \|
  = link_to 'Cancel Editing', @recipe, class: "btn btn-danger"

app/views/recipes/index.html.haml
.container
  .row
    - @recipes.each do |recipe|
      .col-md-4
        .recipe
          .image_wrapper
            = link_to recipe do
              = image_tag recipe.image.url(:medium)
              %h2= link_to recipe.title, recipe
              %p.date= time_ago_in_words(recipe.created_at)

app/views/recipes/new.html.haml
.container
  %h1 Create A Recipe
  = render 'form'
  

app/views/recipes/show.html.haml
.main-content
  #recipe_top.row
    .col-md-4
      = image_tag @recipe.image.url(:medium), class: "recipe_image"
    .col-md-8
      #recipe_info
        %h1= @recipe.title
        %p.description= @recipe.description
        %p
          Recipe By:
          =@recipe.user.name

  .row
    .col-md-6
      #ingredients
        %h2 Ingredients
        %ul
          - @recipe.ingredients.each do |ingredient|
            %li= ingredient.name
    .col-md-6
      #directions
        %h2 Directions
        %ul
          - @recipe.directions.each do |direction|
            %li= direction.step
  .row
    .col-md-12
      = link_to "All Recipes", recipes_path, class: "btn btn-primary"
      - if can? :update, @recipe
        = link_to "Edit Recipe", edit_recipe_path, class: "btn btn-primary"
      - if can? :destroy, @recipe
        = link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-danger"

app/views/welcome/index.html.haml
.container
  %h1 Welcome#index
  %p This is the Place Holder for Nicole's Recipes homepage